# just echo "Hello World"
name: testing git hub actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello World"
      - name: Run a multi-line script
        run: |
          echo "This is the first line"
          echo "This is the second line"
          echo "This is the third line"
      - name: Echo a secret
        run: echo ${{ secrets.ACTIONS_TEST_SECRET }}
      - name: Echo a variable
        run: echo ${{ vars.ACTIONS_TEST_VARIABLE }}
